Azure v2 upgrade
rackerlabs/support-how-to pull request #1380
Opened 2022-06-08 13:11 UTC by Rohi2305

Created an Article for Azure V1 to V2 Migration.

2022-06-08 14:14 UTC, Rohi2305 commented on content/how-to/rackspace-fabric/azure-v2-upgrade/index.md
> +Customer Experience | Azure V1 to V2 Migration
Updated

2022-06-08 14:14 UTC, Rohi2305 commented on content/how-to/rackspace-fabric/azure-v2-upgrade/index.md
> +**Follow the below procedure to access Azure Accounts**
Updated the changes.

2022-06-08 14:15 UTC, Rohi2305 commented on content/how-to/rackspace-fabric/azure-v2-upgrade/index.md
> +**Follow the below procedure to Manage Permissions**
Updated the changes.
Also changed the Switch into Dedicated Account as well.

2022-06-30 15:46 UTC, ssalinas24 requested changes
Bejamin's email is showing in content/how-to/rackspace-fabric/azure-v2-upgrade/Issue Details.png. So take a look at that.

Overall it seems like the new images are not linked from within the file.

2022-07-01 21:50 UTC, ssalinas24 requested changes

2022-07-01 21:50 UTC, ssalinas24 commented on content/how-to/rackspace-fabric/azure-v2-upgrade/index.md
> +**How to access Azure Subscriptions**
```suggestion
## How to access Azure Subscriptions
```

2022-07-01 21:50 UTC, ssalinas24 commented on content/how-to/rackspace-fabric/azure-v2-upgrade/index.md
> +--------------------------------------------
```suggestion
## Accessing Dedicated Hosting Portal
```

2022-07-01 21:50 UTC, ssalinas24 commented on content/how-to/rackspace-fabric/azure-v2-upgrade/index.md
> +**How to switch into Dedicated Hosting Account**
```suggestion
### How to switch into Dedicated Hosting Account
```

2022-07-01 21:50 UTC, ssalinas24 commented on content/how-to/rackspace-fabric/azure-v2-upgrade/index.md
> +-----------------------------
```suggestion
## Managing Permissions
```

2022-07-01 21:50 UTC, ssalinas24 commented on content/how-to/rackspace-fabric/azure-v2-upgrade/index.md
> +**How to manage Azure Permissions**
```suggestion
### How to manage Azure Permissions
```

2022-07-01 21:50 UTC, ssalinas24 commented on content/how-to/rackspace-fabric/azure-v2-upgrade/index.md
> +====================================
```suggestion
## Managing Tickets for Azure v2
```

2022-07-01 21:50 UTC, ssalinas24 commented on content/how-to/rackspace-fabric/azure-v2-upgrade/index.md
> +----------------------------------------
```suggestion
### Viewing Azure v2 Tickets
```

2022-07-01 21:50 UTC, ssalinas24 commented on content/how-to/rackspace-fabric/azure-v2-upgrade/index.md
> +**How to view Azure v2 Tickets**
```suggestion
#### How to view Azure v2 Tickets
```

2022-07-01 21:50 UTC, ssalinas24 commented on content/how-to/rackspace-fabric/azure-v2-upgrade/index.md
> +**Creating a Ticket for Azure v2 Subscriptions**
```suggestion
### Creating a Ticket for Azure v2 Subscriptions
```

2022-07-01 21:50 UTC, ssalinas24 commented on content/how-to/rackspace-fabric/azure-v2-upgrade/index.md
> +**How to Create a Ticket**
```suggestion
#### How to Create a Ticket
```

2022-07-01 21:50 UTC, ssalinas24 commented on content/how-to/rackspace-fabric/azure-v2-upgrade/index.md
> +------------------------------------
```suggestion
```

2022-07-01 22:01 UTC, ssalinas24 requested changes

2022-07-01 22:01 UTC, ssalinas24 commented on content/how-to/rackspace-fabric/azure-v2-upgrade/index.md
> +=======================================
```suggestion
```

2022-07-01 22:11 UTC, ssalinas24 approved these changes

2022-07-01 22:11 UTC, merged